twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'public/images': images
        'public/css': css
        'public/js': js
when@test:
    twig:
        strict_variables: true
